# Generated by Django 4.1.10 on 2023-07-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('artista', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('duracion', models.DurationField()),
            ],
        ),
    ]
